apiVersion: v1
kind: Pod
metadata:
  name: explorer
  labels:
    component: explorer
    tier: test
spec:
  nodeSelector:
    maild: "true"
  containers:
  - image: jtulupov/explorer
    name: explorer
