apiVersion: v1
kind: Pod
metadata:
  name: test-httpd
  labels:
    component: test-httpd
    tier: test
spec:
  nodeSelector:
    maild: "true"
  containers:
  - image: jtulupov/kubia
    name: test-httpd
    ports:
    - containerPort: 8080
      protocol: TCP
